/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/users/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create User */
        post: operations["api_views_create_user"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reset/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Request Password Reset */
        post: operations["api_views_request_password_reset"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reset/confirm/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirm Password Reset */
        post: operations["api_views_confirm_password_reset"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/verify/{token}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Verify Email
         * @description Verify user's email address using the token from the verification email.
         */
        post: operations["api_views_verify_email"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/resend-verification/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Resend Verification Email
         * @description Resend verification email to user.
         */
        post: operations["api_views_resend_verification_email"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ping": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ping */
        get: operations["api_views_ping"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sources/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Sources */
        get: operations["api_views_list_sources"];
        put?: never;
        /** Create Source */
        post: operations["api_views_create_source"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Events */
        get: operations["api_views_list_events"];
        put?: never;
        /** Create Event */
        post: operations["api_views_create_event"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events/{event_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Event */
        get: operations["api_views_get_event"];
        /** Update Event */
        put: operations["api_views_update_event"];
        post?: never;
        /** Delete Event */
        delete: operations["api_views_delete_event"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sites/{domain}/strategy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Site Strategy */
        get: operations["api_views_get_site_strategy"];
        /** Override Site Strategy */
        put: operations["api_views_override_site_strategy"];
        /** Report Site Strategy */
        post: operations["api_views_report_site_strategy"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scrape": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Submit Scrape
         * @description Submit URL for asynchronous processing (frontend endpoint).
         */
        post: operations["api_views_submit_scrape"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scrape/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Scrape Job */
        get: operations["api_views_get_scrape_job"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scrape/{job_id}/results": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Save Scrape Results */
        post: operations["api_views_save_scrape_results"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scrape/batch/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Submit Batch
         * @description Submit multiple URLs for batch processing.
         */
        post: operations["api_views_submit_batch"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scrape/batch/{batch_id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Batch Status */
        get: operations["api_views_batch_status"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/queue/submit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Submit Url To Queue
         * @description Submit URL for asynchronous processing.
         */
        post: operations["api_views_submit_url_to_queue"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/queue/next": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Next Job
         * @description Workers call this to get next job (atomic claim with SELECT FOR UPDATE).
         */
        get: operations["api_views_get_next_job"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/queue/{job_id}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Complete Job
         * @description Worker reports job completion with events.
         */
        post: operations["api_views_complete_job"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/queue/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Queue Status
         * @description Get queue statistics.
         */
        get: operations["api_views_queue_status"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/queue/bulk-submit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Bulk Submit Urls
         * @description Submit multiple URLs for processing (daily re-scrape use case).
         */
        post: operations["api_views_bulk_submit_urls"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/queue/bulk-submit-service": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Bulk Submit Urls Service
         * @description Bulk submit URLs using service token (for administrative bulk loading).
         *     Uses first superuser as the submitter since service tokens don't have users.
         */
        post: operations["api_views_bulk_submit_urls_service"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/chat/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Chat Sessions
         * @description List user's chat sessions, most recent first.
         */
        get: operations["api_views_list_chat_sessions"];
        put?: never;
        /**
         * Create Chat Session
         * @description Create a new chat session.
         */
        post: operations["api_views_create_chat_session"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/chat/sessions/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Chat Session
         * @description Get session with messages.
         */
        get: operations["api_views_get_chat_session"];
        /**
         * Update Chat Session
         * @description Update session title or context.
         */
        put: operations["api_views_update_chat_session"];
        post?: never;
        /**
         * Delete Chat Session
         * @description Permanently delete a session and all its messages.
         */
        delete: operations["api_views_delete_chat_session"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/chat/sessions/{session_id}/archive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Archive Chat Session
         * @description Archive (soft-delete) a session.
         */
        post: operations["api_views_archive_chat_session"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/chat/sessions/{session_id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Session Messages
         * @description Get messages for a session with pagination.
         */
        get: operations["api_views_get_session_messages"];
        put?: never;
        /**
         * Add Session Message
         * @description Add a message to a session (used by chat service or for manual additions).
         */
        post: operations["api_views_add_session_message"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/chat/sessions/{session_id}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Session History For Llm
         * @description Get recent messages formatted for LLM context.
         */
        get: operations["api_views_get_session_history_for_llm"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Live
         * @description Kubernetes liveness probe - is the app running?
         */
        get: operations["api_health_live"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        /**
         * Live
         * @description Kubernetes liveness probe - is the app running?
         */
        head: operations["api_health_live_head"];
        patch?: never;
        trace?: never;
    };
    "/api/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Ready
         * @description Kubernetes readiness probe - can the app serve traffic?
         */
        get: operations["api_health_ready"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        /**
         * Ready
         * @description Kubernetes readiness probe - can the app serve traffic?
         */
        head: operations["api_health_ready_head"];
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Simple health check with build version info.
         */
        get: operations["api_health_health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        /**
         * Health
         * @description Simple health check with build version info.
         */
        head: operations["api_health_health_head"];
        patch?: never;
        trace?: never;
    };
    "/api/health/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Dashboard
         * @description Comprehensive health dashboard for all Superschedules services.
         *     Checks Django, Database, LLM, RAG, Collector, and Navigator.
         *
         *     Returns JSON by default, or HTML if Accept header includes text/html.
         */
        get: operations["api_health_health_dashboard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** UserSchema */
        UserSchema: {
            /** ID */
            id?: number | null;
            /**
             * Username
             * @description Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.
             */
            username: string;
            /** Email Address */
            email?: string | null;
            /** First Name */
            first_name?: string | null;
            /** Last Name */
            last_name?: string | null;
        };
        /** UserCreateSchema */
        UserCreateSchema: {
            /** Email */
            email: string;
            /** Password */
            password: string;
            /** First Name */
            first_name?: string | null;
            /** Last Name */
            last_name?: string | null;
            /** Turnstiletoken */
            turnstileToken?: string | null;
        };
        /** PasswordResetRequestSchema */
        PasswordResetRequestSchema: {
            /** Email */
            email: string;
        };
        /** MessageSchema */
        MessageSchema: {
            /** Message */
            message: string;
        };
        /** PasswordResetConfirmSchema */
        PasswordResetConfirmSchema: {
            /** Token */
            token: string;
            /** Password */
            password: string;
        };
        /** EmailVerificationResendSchema */
        EmailVerificationResendSchema: {
            /** Email */
            email: string;
        };
        /** SourceSchema */
        SourceSchema: {
            /** ID */
            id?: number | null;
            /** Name */
            name?: string | null;
            /** Base Url */
            base_url?: string | null;
            /**
             * Search Method
             * @default manual
             */
            search_method: string;
            /**
             * Status
             * @default not_run
             */
            status: string;
            /**
             * Date Added
             * Format: date-time
             */
            date_added: string;
            /** Last Run At */
            last_run_at?: string | null;
        };
        /** SourceCreateSchema */
        SourceCreateSchema: {
            /** Base Url */
            base_url: string;
            /** Name */
            name?: string | null;
            /** Search Method */
            search_method?: string | null;
        };
        /** EventSchema */
        EventSchema: {
            venue?: components["schemas"]["VenueSchema"] | null;
            /**
             * Room Name
             * @default
             */
            room_name: string;
            /**
             * Location
             * @default
             */
            location: string;
            /** ID */
            id?: number | null;
            /** External Id */
            external_id: string;
            /** Title */
            title: string;
            /** Description */
            description: string;
            /**
             * Start Time
             * Format: date-time
             */
            start_time: string;
            /** End Time */
            end_time?: string | null;
            /** Url */
            url?: string | null;
            /** Metadata Tags */
            metadata_tags?: Record<string, never> | null;
        };
        /** VenueSchema */
        VenueSchema: {
            /** ID */
            id?: number | null;
            /**
             * Name
             * @description Venue name (e.g., 'Waltham Public Library')
             */
            name: string;
            /**
             * Street Address
             * @description Street address (e.g., '735 Main Street')
             */
            street_address?: string | null;
            /**
             * City
             * @description City name
             */
            city: string;
            /**
             * State
             * @description State/region (abbreviation or full name)
             */
            state: string;
            /**
             * Postal Code
             * @description ZIP/postal code
             */
            postal_code?: string | null;
            /**
             * Latitude
             * @description Latitude coordinate
             */
            latitude?: number | string | null;
            /**
             * Longitude
             * @description Longitude coordinate
             */
            longitude?: number | string | null;
        };
        /** EventCreateSchema */
        EventCreateSchema: {
            /** Source Id */
            source_id?: number | null;
            /** External Id */
            external_id: string;
            /** Title */
            title: string;
            /** Description */
            description: string;
            /** Location Data */
            location_data?: {
                [key: string]: unknown;
            } | null;
            /**
             * Start Time
             * Format: date-time
             */
            start_time: string;
            /** End Time */
            end_time?: string | null;
            /** Url */
            url?: string | null;
            /** Metadata Tags */
            metadata_tags?: string[] | null;
            /** Organizer */
            organizer?: string | null;
            /** Event Status */
            event_status?: string | null;
            /** Event Attendance Mode */
            event_attendance_mode?: string | null;
        };
        /** EventUpdateSchema */
        EventUpdateSchema: {
            /** Source Id */
            source_id?: number | null;
            /** External Id */
            external_id?: string | null;
            /** Title */
            title?: string | null;
            /** Description */
            description?: string | null;
            /** Start Time */
            start_time?: string | null;
            /** End Time */
            end_time?: string | null;
            /** Url */
            url?: string | null;
            /** Metadata Tags */
            metadata_tags?: string[] | null;
        };
        /** SiteStrategySchema */
        SiteStrategySchema: {
            /** Domain */
            domain: string;
            /** Best Selectors */
            best_selectors?: Record<string, never> | null;
            /** Pagination Pattern */
            pagination_pattern?: string | null;
            /** Cancellation Indicators */
            cancellation_indicators?: Record<string, never> | null;
            /**
             * Success Rate
             * @default 0
             */
            success_rate: number;
            /**
             * Total Attempts
             * @default 0
             */
            total_attempts: number;
            /**
             * Successful Attempts
             * @default 0
             */
            successful_attempts: number;
            /** Last Successful */
            last_successful?: string | null;
            /** Notes */
            notes?: string | null;
        };
        /** SiteStrategyUpdateSchema */
        SiteStrategyUpdateSchema: {
            /** Best Selectors */
            best_selectors?: string[] | null;
            /** Pagination Pattern */
            pagination_pattern?: string | null;
            /** Cancellation Indicators */
            cancellation_indicators?: string[] | null;
            /** Notes */
            notes?: string | null;
            /** Success */
            success?: boolean | null;
        };
        /** ScrapingJobSchema */
        ScrapingJobSchema: {
            /** ID */
            id?: number | null;
            /** Url */
            url: string;
            /** Domain */
            domain: string;
            /**
             * Status
             * @default pending
             */
            status: string;
            /**
             * Priority
             * @default 5
             */
            priority: number;
            /** Strategy Used */
            strategy_used?: string | null;
            /**
             * Events Found
             * @default 0
             */
            events_found: number;
            /**
             * Pages Processed
             * @default 1
             */
            pages_processed: number;
            /** Processing Time */
            processing_time?: number | null;
            /** Error Message */
            error_message?: string | null;
            /** Lambda Request Id */
            lambda_request_id?: string | null;
            /** Worker Type */
            worker_type?: string | null;
            /** Estimated Cost */
            estimated_cost?: number | string | null;
            /** Extraction Method */
            extraction_method?: string | null;
            /** Confidence Score */
            confidence_score?: number | null;
            /** Locked By */
            locked_by?: string | null;
            /** Locked At */
            locked_at?: string | null;
            /**
             * Retry Count
             * @default 0
             */
            retry_count: number;
            /**
             * Max Retries
             * @default 3
             */
            max_retries: number;
            /** Submitted By */
            submitted_by?: number | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Completed At */
            completed_at?: string | null;
        };
        /** ScrapeRequestSchema */
        ScrapeRequestSchema: {
            /** Url */
            url: string;
        };
        /** ScrapeResultEventSchema */
        ScrapeResultEventSchema: {
            /** External Id */
            external_id: string;
            /** Title */
            title: string;
            /** Description */
            description: string;
            /** Location Data */
            location_data?: {
                [key: string]: unknown;
            } | null;
            /**
             * Start Time
             * Format: date-time
             */
            start_time: string;
            /** End Time */
            end_time?: string | null;
            /** Url */
            url?: string | null;
            /** Metadata Tags */
            metadata_tags?: string[] | null;
            /** Affiliate Link */
            affiliate_link?: string | null;
            /** Revenue Source */
            revenue_source?: string | null;
            /** Commission Rate */
            commission_rate?: number | null;
            /** Affiliate Tracking Id */
            affiliate_tracking_id?: string | null;
        };
        /** ScrapeResultSchema */
        ScrapeResultSchema: {
            /** Events */
            events: components["schemas"]["ScrapeResultEventSchema"][];
            /** Events Found */
            events_found: number;
            /** Pages Processed */
            pages_processed: number;
            /** Processing Time */
            processing_time?: number | null;
            /** Error Message */
            error_message?: string | null;
            /**
             * Success
             * @default true
             */
            success: boolean;
        };
        /** BatchResponseSchema */
        BatchResponseSchema: {
            /** Batch Id */
            batch_id: number;
            /** Job Ids */
            job_ids: number[];
        };
        /** BatchRequestSchema */
        BatchRequestSchema: {
            /** Urls */
            urls: string[];
        };
        /** ChatSessionSchema */
        ChatSessionSchema: {
            /** Id */
            id: number;
            /** Title */
            title: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Is Active */
            is_active: boolean;
            /**
             * Context
             * @default {}
             */
            context: {
                [key: string]: unknown;
            };
            /**
             * Message Count
             * @default 0
             */
            message_count: number;
        };
        /** CreateSessionSchema */
        CreateSessionSchema: {
            /**
             * Title
             * @default
             */
            title: string;
            /**
             * Context
             * @default {}
             */
            context: {
                [key: string]: unknown;
            };
        };
        /** ChatMessageSchema */
        ChatMessageSchema: {
            /** Id */
            id: number;
            /** Role */
            role: string;
            /** Content */
            content: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Metadata
             * @default {}
             */
            metadata: {
                [key: string]: unknown;
            };
        };
        /** ChatSessionDetailSchema */
        ChatSessionDetailSchema: {
            /** Id */
            id: number;
            /** Title */
            title: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Is Active */
            is_active: boolean;
            /**
             * Context
             * @default {}
             */
            context: {
                [key: string]: unknown;
            };
            /**
             * Messages
             * @default []
             */
            messages: components["schemas"]["ChatMessageSchema"][];
        };
        /** UpdateSessionSchema */
        UpdateSessionSchema: {
            /** Title */
            title?: string | null;
            /** Context */
            context?: {
                [key: string]: unknown;
            } | null;
        };
        /** AddMessageSchema */
        AddMessageSchema: {
            /** Role */
            role: string;
            /** Content */
            content: string;
            /**
             * Metadata
             * @default {}
             */
            metadata: {
                [key: string]: unknown;
            };
            /**
             * Event Ids
             * @default []
             */
            event_ids: number[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    api_views_create_user: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserCreateSchema"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserSchema"];
                };
            };
        };
    };
    api_views_request_password_reset: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordResetRequestSchema"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_views_confirm_password_reset: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordResetConfirmSchema"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageSchema"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageSchema"];
                };
            };
        };
    };
    api_views_verify_email: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageSchema"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageSchema"];
                };
            };
        };
    };
    api_views_resend_verification_email: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmailVerificationResendSchema"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageSchema"];
                };
            };
        };
    };
    api_views_ping: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_views_list_sources: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceSchema"][];
                };
            };
        };
    };
    api_views_create_source: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SourceCreateSchema"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceSchema"];
                };
            };
        };
    };
    api_views_list_events: {
        parameters: {
            query?: {
                start?: string | null;
                end?: string | null;
                ids?: number[];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventSchema"][];
                };
            };
        };
    };
    api_views_create_event: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EventCreateSchema"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventSchema"];
                };
            };
        };
    };
    api_views_get_event: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                event_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventSchema"];
                };
            };
        };
    };
    api_views_update_event: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                event_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EventUpdateSchema"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventSchema"];
                };
            };
        };
    };
    api_views_delete_event: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                event_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_views_get_site_strategy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                domain: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SiteStrategySchema"];
                };
            };
        };
    };
    api_views_override_site_strategy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                domain: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SiteStrategyUpdateSchema"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SiteStrategySchema"];
                };
            };
        };
    };
    api_views_report_site_strategy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                domain: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SiteStrategyUpdateSchema"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SiteStrategySchema"];
                };
            };
        };
    };
    api_views_submit_scrape: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScrapeRequestSchema"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScrapingJobSchema"];
                };
            };
        };
    };
    api_views_get_scrape_job: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScrapingJobSchema"];
                };
            };
        };
    };
    api_views_save_scrape_results: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScrapeResultSchema"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_views_submit_batch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BatchRequestSchema"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BatchResponseSchema"];
                };
            };
        };
    };
    api_views_batch_status: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                batch_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScrapingJobSchema"][];
                };
            };
        };
    };
    api_views_submit_url_to_queue: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScrapeRequestSchema"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScrapingJobSchema"];
                };
            };
        };
    };
    api_views_get_next_job: {
        parameters: {
            query: {
                worker_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScrapingJobSchema"];
                };
            };
        };
    };
    api_views_complete_job: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScrapeResultSchema"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_views_queue_status: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_views_bulk_submit_urls: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BatchRequestSchema"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_views_bulk_submit_urls_service: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BatchRequestSchema"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_views_list_chat_sessions: {
        parameters: {
            query?: {
                active_only?: boolean;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatSessionSchema"][];
                };
            };
        };
    };
    api_views_create_chat_session: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSessionSchema"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatSessionSchema"];
                };
            };
        };
    };
    api_views_get_chat_session: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatSessionDetailSchema"];
                };
            };
        };
    };
    api_views_update_chat_session: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateSessionSchema"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatSessionSchema"];
                };
            };
        };
    };
    api_views_delete_chat_session: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_views_archive_chat_session: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_views_get_session_messages: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                session_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatMessageSchema"][];
                };
            };
        };
    };
    api_views_add_session_message: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddMessageSchema"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatMessageSchema"];
                };
            };
        };
    };
    api_views_get_session_history_for_llm: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                session_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_health_live: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_health_live_head: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_health_ready: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_health_ready_head: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_health_health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_health_health_head: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_health_health_dashboard: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
}
