name: Claude Code

on:
  issue_comment:
    types: [created, edited]
  pull_request_review_comment:
    types: [created, edited]

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  claude-code:
    runs-on: ubuntu-latest
    # Only run if the comment includes @claude
    if: |
      (github.event_name == 'issue_comment' && contains(github.event.comment.body, '@claude')) ||
      (github.event_name == 'pull_request_review_comment' && contains(github.event.comment.body, '@claude'))
    steps:
      - uses: actions/checkout@v4
      - name: Run Claude Code
        id: claude
        uses: anthropics/claude-code-action@v0.0.60
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          # optional: allowed_tools, timeout_minutes, etc.
