name: Claude Code

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  claude-code:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      issues: write
    steps:
      - name: Claude Code
        uses: anthropics/claude-code@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}